#!/bin/bash

DIR=$(cat rootdir.txt)/tickets

for f in $(ls -v $DIR/*)
do
        echo $(basename $f)
        echo "---------------------------"
        cat $f
        echo "---------------------------"
        echo
done
